"""
Gemini API client for the music recommender.

Handles API key loading, client initialization, and text generation.
"""

import os
import logging
from typing import Optional
from dotenv import load_dotenv
import google.generativeai as genai

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables from .env file
load_dotenv()

# Get API key. Produce an error if API key is not found.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    logger.error("GEMINI_API_KEY not found in environment variables. Please set it in .env file.")
    raise ValueError("GEMINI_API_KEY is required.")

# Configure Gemini
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-1.5-flash")  # Use the fast model for efficiency

def generate_text(prompt: str, max_tokens: int = 500) -> Optional[str]:
    """
    Generate text using Gemini API.

    Args:
        prompt: The input prompt for generation.
        max_tokens: Maximum tokens to generate (approximate).

    Returns:
        Generated text or None if error.
    """
    try:
        logger.info("Sending prompt to Gemini API.")
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                max_output_tokens=max_tokens,
                temperature=0.7,  # Balanced creativity
            )
        )
        if response and response.text:
            logger.info("Successfully received response from Gemini.")
            return response.text.strip()
        else:
            logger.warning("No text generated by Gemini.")
            return None
    except Exception as e:
        logger.error(f"Error generating text with Gemini: {e}")
        return None