"""
Gemini API client for the music recommender.

Handles API key loading, client initialization, and text generation.
"""

import os
import logging
from typing import Optional
from dotenv import load_dotenv
from google import genai
from google.genai import types

logger = logging.getLogger(__name__)

# Load environment variables from .env file
load_dotenv()

# Get API key. Produce an error if API key is not found.
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    logger.error("\nGEMINI_API_KEY not found in environment variables. Please set it in .env file.")
    raise ValueError("\nGEMINI_API_KEY is required.")

client = genai.Client(api_key=GEMINI_API_KEY)

def generate_text(prompt: str, max_tokens: int = 500) -> Optional[str]:
    """
    Generate text using Gemini API.

    Args:
        prompt: The input prompt for generation.
        max_tokens: Maximum tokens to generate (approximate).

    Returns:
        Generated text or None if error.
    """
    try:
        logger.info("\n\nSending prompt to Gemini API.\n")
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=max_tokens,
                temperature=0.7,
            )
        )
        if response.text:
            logger.info("\n\nSuccessfully received response from Gemini.")
            return response.text.strip()
        else:
            logger.warning("\n\nNo text generated by Gemini.")
            return None
    except Exception as e:
        msg = str(e.args[0]).split('{')[0].strip() if e.args else ''
        logger.error(f"\n\nError generating text with Gemini: {type(e).__name__}: {msg}")
        return None